# Generated by Django 3.2.7 on 2021-09-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_entery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=90)),
                ('desc', models.TextField()),
            ],
        ),
    ]
